version: "3"
services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-admin}
    volumes:
      - redis_data:/data
    restart: always
    ports:
      - "6379:6379"
volumes:
  redis_data:
